#!/bin/sh

IMAGE=nasphotos-thumbnails
VOLUME=/mnt/media/Pictures:/data
DOCKER_MEMORY=72m
XMX=64
docker run -ti --rm -m ${DOCKER_MEMORY} -v ${VOLUME} -e MEMORY_LIMIT=${XMX} -e PHOTOPATH=/data ${IMAGE}
