FROM fabric8/java-alpine-openjdk8-jre
ENV AB_ENABLED=jmx_exporter
ENV PORT=8081
COPY target/lib/* /deployments/lib/
COPY target/*-runner.jar /deployments/app.jar
EXPOSE 8081
VOLUME ["/data"]

RUN adduser -G root --no-create-home --disabled-password 1001 \
  && chown -R 1001 /deployments \
  && chmod -R "g+rwX" /deployments \
  && chown -R 1001:root /deployments \
  && mkdir -p /data

CMD cd /deployments && java -Dquarkus.http.port=${PORT} -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar app.jar
